------
## Wstęp do Eksploracji Danych
### Laboratorium 12
------

## 0. Obsługa jupyter notebook

#### edycja - podświetlenie zielone
`shift` + `enter` - wywołanie komórki i przejście do kolejnej (stworzenie kolejnej)

`ctrl` + `enter` = wywołanie komórki

#### wybór - podświetlenie niebieskie
`A` - stworzenie komórki nad obecną komórką (Above)

`B` - stworzenie komórski pod obecną komórką (Below)

`D` + `D` - usunięcie podświetlonej komórki

#### typ komórki
`ctrl` + `M` - code > markdown 

`ctrl` + `Y` - markdown > code 


#### gdy nie wiemy jak działa dana funkcja w biblitece
`shift` + `tab` - wyświetlenie dokumentacji (DocString)


# 1. NumPy 

In [1]:
import numpy as np

## 1.1 Typy danych w tablicach numpy 

In [2]:
# lista
[1, 2, 3, 4, 5]

[1, 2, 3, 4, 5]

In [3]:
# lista array
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [4]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [5]:
type(a)

numpy.ndarray

In [6]:
# typ listy zależny od tego co wrzucimy do listy 
a.dtype

dtype('int32')

`dtype` - typ skalarów w liście

In [7]:
np.array([1, 2, 3, 4, 5], dtype = "float32")

array([1., 2., 3., 4., 5.], dtype=float32)

In [8]:
np.array([1, 2, 3, 4, 5], dtype = "str") # zwraca unicode

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [9]:
# co się stanie jak float znajdzie się w liście intów?
np.array([1, 2, 3.14, 2.9123412312], dtype = "int64")

array([1, 2, 3, 2], dtype=int64)

In [10]:
# co się stanie jak napis znajdzie się w liście intów?
np.array([1, 2, 3, "słoń"])

array(['1', '2', '3', 'słoń'], dtype='<U11')

## 1.2 Tworzenie tablic w numpy

In [11]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [12]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [13]:
[i for i in range(3, 10, 2)]

[3, 5, 7, 9]

In [14]:
np.arange(3, 10, 2)

array([3, 5, 7, 9])

In [15]:
# lista zer
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
# lista jedynek
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
# repeat
np.repeat(3, 5)

array([3, 3, 3, 3, 3])

In [18]:
np.repeat([3, 4], 4)

array([3, 3, 3, 3, 4, 4, 4, 4])

In [19]:
np.array([3, 4]).repeat(2).repeat(2)

array([3, 3, 3, 3, 4, 4, 4, 4])

In [20]:
np.array([3, 4]).repeat([1,3])

array([3, 4, 4, 4])

In [21]:
# bardziej intuicyjne
np.tile([3, 4], 3)

array([3, 4, 3, 4, 3, 4])

## 1.3 ndarray - wielowymiarowość

In [22]:
a = [[1, 2, 3],
     [1, 2, 3]]

b = np.array(a)
b

array([[1, 2, 3],
       [1, 2, 3]])

In [23]:
# wymiar
b.ndim

2

In [24]:
# ksztalt - ile wierszy, kolumn
b.shape

(2, 3)

In [25]:
c = np.ones(24, dtype = "int32")

In [26]:
c.shape

(24,)

In [27]:
c.reshape(24, 1)

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [28]:
c.reshape(4, 6)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

**Uwaga!** możemy wykonywać `reshape` dopóki `shape` pomieści dokładnie tyle danych ile elementów ma pierwotna lista.

In [29]:
c.reshape(4, 5)

ValueError: cannot reshape array of size 24 into shape (4,5)

In [30]:
# do jednego wymiaru
d = c.flatten()
d

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

In [31]:
d.reshape(4, 3, 2) # lista mająca 4 listy, które mają 3 listy po 2 elementy

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

## 1.4 Indeksowanie

In [32]:
a = np.arange(20).reshape(4, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [33]:
a[2]

array([10, 11, 12, 13, 14])

In [34]:
a[1:3]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [35]:
a[1:3, 2:4]

array([[ 7,  8],
       [12, 13]])

In [36]:
a[:, 1:5]

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19]])

In [37]:
a > 10

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [38]:
a[a > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [39]:
(a > 3) and (a < 10)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [40]:
a > 3 & a < 10

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [41]:
(a > 3) & (a < 10)

array([[False, False, False, False,  True],
       [ True,  True,  True,  True,  True],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [42]:
a[(a > 3) & (a < 10)]

array([4, 5, 6, 7, 8, 9])

In [43]:
a[(a > 3) | (a < 10)]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [44]:
# szukanie indeksów
index = np.where((a > 3) & (a < 10))
index
# krotka, pierwsza lista wskazuje wiersz, druga lista wskazuje kolumny

(array([0, 1, 1, 1, 1, 1], dtype=int64),
 array([4, 0, 1, 2, 3, 4], dtype=int64))

### Zadania 1.1
-----------

1. Stwórz macierz
\begin{bmatrix}
1 & 2 & 3 & 4 & 5 \\
6 & 7 & 8 & 9 & 10 \\
11 & 12 & 13 & 14 & 15
\end{bmatrix}

2. Spróbuj indeksami dostać się do poniższych elementów 

a)
\begin{bmatrix}
6 & 7 & 8 & 9 & 10 \\
\end{bmatrix}

b)
\begin{bmatrix}
4 \\
9 \\
14 
\end{bmatrix}

c)
\begin{bmatrix}
9 & 10 \\
14 & 15
\end{bmatrix}


3. Znajdź indeksy wartości mniejszych niż 10, ale większych od 4

In [ ]:
# 1)

A = np.arange(1, 16).reshape([3, 5])
print("1)", A)

# 2) 
# a)

A[1]

print("2) a)", A[1])
# b)

A[:, 3]

print("2) b)", A[:, 3])
# c)

A[1:, 3:]

print("2) c)", A[1:, 3:])

# 3)

np.where((A > 4) & (A < 10))

print("3)", np.where((A > 4) & (A < 10)))

1) [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
2) a) [ 6  7  8  9 10]
2) b) [ 4  9 14]
2) c) [[ 9 10]
 [14 15]]
3) (array([0, 1, 1, 1, 1], dtype=int64), array([4, 0, 1, 2, 3], dtype=int64))


# 2. Operacje na tablicach

## 2.1 Podstawowe działania

In [48]:
# listy a, b
a = np.array([1, 1, 2, 1])
b = np.array([1, 2, 3, 4])

In [50]:
print(a + 3)
print(a * 3)

[4 4 5 4]
[3 3 6 3]


In [51]:
print(a + b)
print(a - b)
a/b

[2 3 5 5]
[ 0 -1 -1 -3]


array([1.        , 0.5       , 0.66666667, 0.25      ])

In [52]:
a = np.arange(5)
b = np.repeat(2, 4)

a + b

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

## 2.2 Metody obiektów ndarray

In [53]:
a = np.arange(10, 21)

In [54]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [55]:
a.mean()

15.0

In [56]:
print(a.sum())
a.max()
a.min()
a.argmax() # indeks maksymalnej wartości

165


10

In [57]:
a.cumsum()

array([ 10,  21,  33,  46,  60,  75,  91, 108, 126, 145, 165])

In [58]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [59]:
a.sum(axis = 0)

165

In [60]:
A = np.arange(5*5).reshape(5,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [61]:
A.sum()

300

In [62]:
print(A.sum(axis = 0))
print(A.sum(axis = 1))

[50 55 60 65 70]
[ 10  35  60  85 110]


In [64]:
print(A.max(axis = 0))
A.min(axis = 1)

[20 21 22 23 24]


array([ 0,  5, 10, 15, 20])

In [65]:
b = np.array([1, -1, 1, -1, 1])

In [66]:
A * b

array([[  0,  -1,   2,  -3,   4],
       [  5,  -6,   7,  -8,   9],
       [ 10, -11,  12, -13,  14],
       [ 15, -16,  17, -18,  19],
       [ 20, -21,  22, -23,  24]])

In [67]:
A * b.reshape(5, 1)

array([[  0,   1,   2,   3,   4],
       [ -5,  -6,  -7,  -8,  -9],
       [ 10,  11,  12,  13,  14],
       [-15, -16, -17, -18, -19],
       [ 20,  21,  22,  23,  24]])

In [68]:
B = np.arange(50).reshape(5, 10)
B

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [69]:
A @ B

array([[ 300,  310,  320,  330,  340,  350,  360,  370,  380,  390],
       [ 800,  835,  870,  905,  940,  975, 1010, 1045, 1080, 1115],
       [1300, 1360, 1420, 1480, 1540, 1600, 1660, 1720, 1780, 1840],
       [1800, 1885, 1970, 2055, 2140, 2225, 2310, 2395, 2480, 2565],
       [2300, 2410, 2520, 2630, 2740, 2850, 2960, 3070, 3180, 3290]])

In [70]:
np.dot(A, B)

array([[ 300,  310,  320,  330,  340,  350,  360,  370,  380,  390],
       [ 800,  835,  870,  905,  940,  975, 1010, 1045, 1080, 1115],
       [1300, 1360, 1420, 1480, 1540, 1600, 1660, 1720, 1780, 1840],
       [1800, 1885, 1970, 2055, 2140, 2225, 2310, 2395, 2480, 2565],
       [2300, 2410, 2520, 2630, 2740, 2850, 2960, 3070, 3180, 3290]])

### Zadania 2.1
-----------

Napisz funkcję `dzialanie`, która jako argumenty przyjmuje dwie listy A i B (o wymiarach (20, )), a następnie konwertuje je do macierzy, która ma 4 wiersze i 5 kolumn. W kolejnym kroku na tak powstałych macierzach wykonaj operacje:

1. Kolumna `A` o indeksie 2 jest mnożona przez sumę wiersza `B` o indeksie 3.
2. Kolumna `A` o indeksie 4 jest zamieniona przez kolumnę `B` o indeksie 1 pomnożoną przez -2.
3. Macierz `C` to macierz powstała z kroków 1 i 2.
4. Co druga kolumna macierzy C jest mnożona przez 2.

In [ ]:
def dzialanie(A, B):
    """
    Funkcja wykonuje działanie.
    A - lista ...
    B - lista ...
    """
    

    A, B = A.reshape(4, 5), B.reshape(4, 5)
    C = A.copy()
    C[:, 2] *= B[3].sum()
    C[:, 4] = B[:, 1] * (-2)
    C[:, ::2] *= 2    
    return C

In [72]:
A = np.arange(1, 21)
B = np.arange(20, 40)

dzialanie(A, B)

array([[   2,    2, 1110,    4,  -84],
       [  12,    7, 2960,    9, -104],
       [  22,   12, 4810,   14, -124],
       [  32,   17, 6660,   19, -144]])

In [ ]:
# array([[   2,    2, 1110,    4,  -84],
#        [  12,    7, 2960,    9, -104],
#        [  22,   12, 4810,   14, -124],
#        [  32,   17, 6660,   19, -144]])

# 3. Wprowadzenie do pandas

## 3.1 Podstawy

In [73]:
import pandas as pd

In [74]:
# import danych
df = pd.read_csv("https://raw.githubusercontent.com/R-Ladies-Warsaw/PoweR/master/Cz%C4%99%C5%9B%C4%87%202%20-%20Formatowanie%20danych/Python/data/vgsales.csv",
                delimiter = ",").dropna().reset_index(drop = True)

In [75]:
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16286,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16287,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16288,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16289,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01


In [76]:
df.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37


In [77]:
df = df.drop("Rank", axis = 1)

In [78]:
df

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...
16286,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16287,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16288,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16289,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01


## 3.1.1 Atrybuty pd.DataFrame

In [79]:
df.index

RangeIndex(start=0, stop=16291, step=1)

In [80]:
type(df.index)

pandas.core.indexes.range.RangeIndex

In [81]:
df.columns

Index(['Name', 'Platform', 'Year', 'Genre', 'Publisher', 'NA_Sales',
       'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales'],
      dtype='object')

In [82]:
df.dtypes

Name             object
Platform         object
Year            float64
Genre            object
Publisher        object
NA_Sales        float64
EU_Sales        float64
JP_Sales        float64
Other_Sales     float64
Global_Sales    float64
dtype: object

In [83]:
df.axes

[RangeIndex(start=0, stop=16291, step=1),
 Index(['Name', 'Platform', 'Year', 'Genre', 'Publisher', 'NA_Sales',
        'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales'],
       dtype='object')]

In [84]:
df.shape

(16291, 10)

## 3.1.2 Wybieranie kolumn

In [85]:
df["Platform"]

0        Wii
1        NES
2        Wii
3        Wii
4         GB
        ... 
16286    GBA
16287     GC
16288    PS2
16289     DS
16290    GBA
Name: Platform, Length: 16291, dtype: object

In [86]:
df.JP_Sales

0         3.77
1         6.81
2         3.79
3         3.28
4        10.22
         ...  
16286     0.00
16287     0.00
16288     0.00
16289     0.00
16290     0.00
Name: JP_Sales, Length: 16291, dtype: float64

In [87]:
df[["Platform", "Name"]]

,Platform,Name
0,Wii,Wii Sports
1,NES,Super Mario Bros.
2,Wii,Mario Kart Wii
3,Wii,Wii Sports Resort
4,GB,Pokemon Red/Pokemon Blue
...,...,...
16286,GBA,Woody Woodpecker in Crazy Castle 5
16287,GC,Men in Black II: Alien Escape
16288,PS2,SCORE International Baja 1000: The Official Game
16289,DS,Know How 2


## 3.2 Indeksowanie

Główne sposoby indeksowania:

1. []
2. .iloc[]
3. .loc[]

In [88]:
np.random.seed(123)

In [89]:
smalldf = df.iloc[np.random.randint(0, df.shape[0], 10),:].reset_index(drop = True)

In [90]:
smalldf

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,The Godfather (old US sales),XB,2006.0,Action,Electronic Arts,0.42,0.11,0.00,0.02,0.55
1,Nobunaga no Yabou Online: Houou no Shou,PS3,2012.0,Strategy,Ackkstudios,0.00,0.00,0.01,0.00,0.01
2,Romance of the Three Kingdoms XI,PS2,2007.0,Strategy,Tecmo Koei,0.00,0.00,0.07,0.00,0.07
3,Sonic Generations,X360,2011.0,Platform,Sega,0.71,0.57,0.00,0.14,1.42
4,Vexx,GC,2003.0,Platform,Acclaim Entertainment,0.05,0.01,0.00,0.00,0.06
5,Angry Birds Star Wars,Wii,2013.0,Strategy,Activision,0.21,0.10,0.00,0.03,0.35
6,Saru! Get You! SaruSaru Daisakusen,PSP,2007.0,Platform,Sony Computer Entertainment,0.00,0.00,0.03,0.00,0.03
7,Barnyard Blast: Swine of the Night,DS,2008.0,Platform,Big Ben Interactive,0.02,0.00,0.00,0.00,0.02
8,God Eater Resurrection,PSV,2015.0,Action,Namco Bandai Games,0.00,0.00,0.19,0.00,0.19
9,Star Trek: The Game,PC,2013.0,Action,Namco Bandai Games,0.00,0.02,0.00,0.00,0.03


### Sposób 1) []

In [91]:
smalldf["Year"]

0    2006.0
1    2012.0
2    2007.0
3    2011.0
4    2003.0
5    2013.0
6    2007.0
7    2008.0
8    2015.0
9    2013.0
Name: Year, dtype: float64

In [92]:
smalldf[0::2] # dla obserwacji

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,The Godfather (old US sales),XB,2006.0,Action,Electronic Arts,0.42,0.11,0.00,0.02,0.55
2,Romance of the Three Kingdoms XI,PS2,2007.0,Strategy,Tecmo Koei,0.00,0.00,0.07,0.00,0.07
4,Vexx,GC,2003.0,Platform,Acclaim Entertainment,0.05,0.01,0.00,0.00,0.06
6,Saru! Get You! SaruSaru Daisakusen,PSP,2007.0,Platform,Sony Computer Entertainment,0.00,0.00,0.03,0.00,0.03
8,God Eater Resurrection,PSV,2015.0,Action,Namco Bandai Games,0.00,0.00,0.19,0.00,0.19


In [93]:
# nie można łączyć
smalldf[0:4, 1]

InvalidIndexError: (slice(0, 4, None), 1)

### Sposób 2) .loc[]

In [94]:
smalldf.loc[0:4, ["Name", "Platform"]]

,Name,Platform
0,The Godfather (old US sales),XB
1,Nobunaga no Yabou Online: Houou no Shou,PS3
2,Romance of the Three Kingdoms XI,PS2
3,Sonic Generations,X360
4,Vexx,GC


In [95]:
smalldf.loc[0:4, smalldf.columns[0:4]]

,Name,Platform,Year,Genre
0,The Godfather (old US sales),XB,2006.0,Action
1,Nobunaga no Yabou Online: Houou no Shou,PS3,2012.0,Strategy
2,Romance of the Three Kingdoms XI,PS2,2007.0,Strategy
3,Sonic Generations,X360,2011.0,Platform
4,Vexx,GC,2003.0,Platform


In [96]:
smalldf.loc[smalldf.Global_Sales > 1]

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
3,Sonic Generations,X360,2011.0,Platform,Sega,0.71,0.57,0.0,0.14,1.42


In [97]:
smalldf.loc[(smalldf.Genre == "Platform") & (smalldf.Year < 2010)]

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
4,Vexx,GC,2003.0,Platform,Acclaim Entertainment,0.05,0.01,0.00,0.0,0.06
6,Saru! Get You! SaruSaru Daisakusen,PSP,2007.0,Platform,Sony Computer Entertainment,0.00,0.00,0.03,0.0,0.03
7,Barnyard Blast: Swine of the Night,DS,2008.0,Platform,Big Ben Interactive,0.02,0.00,0.00,0.0,0.02


### Sposób 3) .iloc[]

In [98]:
smalldf.iloc[0:3, 3:5]

,Genre,Publisher
0,Action,Electronic Arts
1,Strategy,Ackkstudios
2,Strategy,Tecmo Koei


In [99]:
smalldf.iloc[[0, 1, 2], [3, 4]]

,Genre,Publisher
0,Action,Electronic Arts
1,Strategy,Ackkstudios
2,Strategy,Tecmo Koei


In [100]:
smalldf.iloc[2:10:3, 2:10:2]

,Year,Publisher,EU_Sales,Other_Sales
2,2007.0,Tecmo Koei,0.0,0.00
5,2013.0,Activision,0.1,0.03
8,2015.0,Namco Bandai Games,0.0,0.00


**Komentarz:**

- gdy chcemy kolumnę po nazwie - []
- gdy chcemy obserwacje, kolumny po wartościach logicznych lub ich nazwach - .loc[]
- gdy chcemy obserwacje, kolumny po ich pozycji - .iloc[]

## 3.3 Metody ramki danych

In [101]:
df.Name

0                                              Wii Sports
1                                       Super Mario Bros.
2                                          Mario Kart Wii
3                                       Wii Sports Resort
4                                Pokemon Red/Pokemon Blue
                               ...                       
16286                  Woody Woodpecker in Crazy Castle 5
16287                       Men in Black II: Alien Escape
16288    SCORE International Baja 1000: The Official Game
16289                                          Know How 2
16290                                    Spirits & Spells
Name: Name, Length: 16291, dtype: object

In [102]:
df.Name.count()

16291

In [103]:
df.Name.unique()
df.Name.unique().shape

(11325,)

In [104]:
df.Year.mode()
df.Global_Sales.median()
df.Global_Sales.max()

82.74

In [105]:
df.describe()

,Year,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
count,16291.000000,16291.000000,16291.000000,16291.000000,16291.000000,16291.000000
mean,2006.405561,0.265647,0.147731,0.078833,0.048426,0.540910
std,5.832412,0.822432,0.509303,0.311879,0.190083,1.567345
min,1980.000000,0.000000,0.000000,0.000000,0.000000,0.010000
25%,2003.000000,0.000000,0.000000,0.000000,0.000000,0.060000
50%,2007.000000,0.080000,0.020000,0.000000,0.010000,0.170000
75%,2010.000000,0.240000,0.110000,0.040000,0.040000,0.480000
max,2020.000000,41.490000,29.020000,10.220000,10.570000,82.740000


In [106]:
# ile gier sprzedało się w nakładzie większym niż 1 mln
df.loc[df.Global_Sales > 1].shape

(2031, 10)

In [107]:
# jaki procent wszystkich gier
df.Global_Sales[df.Global_Sales > 1].count()/df.Global_Sales.count()*100

12.467006322509361

In [108]:
year_min = df.Year.argmin()
year_min

257

In [109]:
df.Year[year_min]

1980.0

In [110]:
df.EU_Sales.sort_values(ascending = False)

0        29.02
2        12.88
3        11.01
10       11.00
16        9.27
         ...  
10483     0.00
10482     0.00
10479     0.00
10478     0.00
16290     0.00
Name: EU_Sales, Length: 16291, dtype: float64

In [111]:
df.EU_Sales.sort_values(ascending = False).head()

0     29.02
2     12.88
3     11.01
10    11.00
16     9.27
Name: EU_Sales, dtype: float64

In [112]:
df.EU_Sales.sort_values(ascending = False).reset_index().head()

,index,EU_Sales
0,0,29.02
1,2,12.88
2,3,11.01
3,10,11.00
4,16,9.27


In [113]:
df.EU_Sales.sort_values(ascending = False).reset_index(drop = True).head()

0    29.02
1    12.88
2    11.01
3    11.00
4     9.27
Name: EU_Sales, dtype: float64

In [114]:
df.sort_values(["Genre", "Platform"]).reset_index(drop = True).head()

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,Frogger,2600,1981.0,Action,Parker Bros.,2.06,0.12,0.0,0.02,2.20
1,E.T.: The Extra Terrestrial,2600,1981.0,Action,Atari,1.84,0.11,0.0,0.02,1.97
2,Spider-Man,2600,1981.0,Action,Parker Bros.,0.87,0.05,0.0,0.01,0.93
3,Custer's Revenge,2600,1981.0,Action,Mystique,0.76,0.05,0.0,0.01,0.82
4,Alien,2600,1981.0,Action,20th Century Fox Video Games,0.74,0.04,0.0,0.01,0.79


### Zadanie 3.1
---------
Wybierz gry, które sprzedały się lepiej w Europie niż w Ameryce Północnej. Ile ich było? Jaki to procent wszystkich gier?

In [ ]:
df.loc[df.EU_Sales > df.NA_Sales].shape[0] # 2446
df.loc[df.EU_Sales > df.NA_Sales].shape[0]/df.shape[0]*100 # ~15%

15.014425142716837

## 3.5 groupby & merge

In [119]:
df.groupby("Genre")

In [120]:
df.groupby("Genre").Name

In [121]:
df.groupby("Genre")[["Name", "Global_Sales"]]

In [122]:
df.groupby("Genre").Name.agg("count")

Genre
Action          3251
Adventure       1274
Fighting         836
Misc            1686
Platform         875
Puzzle           570
Racing          1225
Role-Playing    1470
Shooter         1282
Simulation       848
Sports          2304
Strategy         670
Name: Name, dtype: int64

In [123]:
df.groupby("Genre").Global_Sales.agg("sum")

Genre
Action          1722.84
Adventure        234.59
Fighting         444.05
Misc             789.87
Platform         829.13
Puzzle           242.21
Racing           726.76
Role-Playing     923.83
Shooter         1026.20
Simulation       389.98
Sports          1309.24
Strategy         173.27
Name: Global_Sales, dtype: float64

In [128]:
df2 = df.groupby(["Genre", "Platform"])[["Global_Sales", "Name"]].agg("max")
df2.reset_index()

,Genre,Platform,Global_Sales,Name
0,Action,2600,2.20,X-Man
1,Action,3DS,4.58,Zyuden Sentai Kyoryuger: Game de Gaburincho!!
2,Action,DC,1.14,Resident Evil - Code: Veronica
3,Action,DS,11.90,Zombi Daisuki
4,Action,GB,3.83,The Legend of Zelda: Oracle of Ages
...,...,...,...,...
288,Strategy,Wii,0.66,Yu-Gi-Oh! 5D's: Duel Transer
289,Strategy,WiiU,1.11,Romance of the Three Kingdoms XII
290,Strategy,X360,2.63,Zoids Assault
291,Strategy,XB,0.73,Yu-Gi-Oh! The Dawn of Destiny


In [129]:
df2

Global_Sales                                           Name
Genre    Platform                                                             
Action   2600              2.20                                          X-Man
         3DS               4.58  Zyuden Sentai Kyoryuger: Game de Gaburincho!!
         DC                1.14                 Resident Evil - Code: Veronica
         DS               11.90                                  Zombi Daisuki
         GB                3.83            The Legend of Zelda: Oracle of Ages
...                         ...                                            ...
Strategy Wii               0.66                   Yu-Gi-Oh! 5D's: Duel Transer
         WiiU              1.11              Romance of the Three Kingdoms XII
         X360              2.63                                  Zoids Assault
         XB                0.73                  Yu-Gi-Oh! The Dawn of Destiny
         XOne              0.20                                         XCOM 2

[293 rows x 2 columns]

In [130]:
df3 = df.groupby("Platform").Global_Sales.agg("sum")

In [131]:
df3 = df3.to_frame()
df3 = df3.reset_index()

In [132]:
df3.head()

,Platform,Global_Sales
0,2600,86.57
1,3DO,0.10
2,3DS,246.27
3,DC,15.97
4,DS,818.91


In [133]:
df4 = df.merge(df3, on = "Platform")

In [134]:
df4

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales_x,Global_Sales_y
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,909.81
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,251.07
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,909.81
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,909.81
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,254.42
...,...,...,...,...,...,...,...,...,...,...,...
16286,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01,305.62
16287,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01,197.14
16288,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01,1233.46
16289,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01,818.91


In [135]:
df4 = df4.rename(columns = {'Global_Sales_y' : "Platform_Global_Sales",
                     'Global_Sales_x' : "Global_Sales"})

### Zadanie 3.2
--------

Które gry sprzedały się najlepiej w swojej kategorii?

In [136]:
df.loc[df.Global_Sales.isin(df.groupby("Genre")["Global_Sales"].max()), :]

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
5,Tetris,GB,1989.0,Puzzle,Nintendo,23.20,2.26,4.22,0.58,30.26
7,Wii Play,Wii,2006.0,Misc,Nintendo,14.03,9.20,2.93,2.85,29.02
9,Duck Hunt,NES,1984.0,Shooter,Nintendo,26.93,0.63,0.28,0.47,28.31
10,Nintendogs,DS,2005.0,Simulation,Nintendo,9.07,11.00,1.93,2.75,24.76
16,Grand Theft Auto V,PS3,2013.0,Action,Take-Two Interactive,7.01,9.27,0.97,4.14,21.40
39,Super Smash Bros. Brawl,Wii,2008.0,Fighting,Nintendo,6.75,2.61,2.66,1.02,13.04


### Zadanie 3.3
------
Jaka była sprzedaż gier na konsolę w 2 roku ich sprzedaży. Pokaż tylko te konsole, w których sprzedaż w 2 roku była mniejsza niż w 1.

Kolumna "Platform".

In [137]:
start_year = df.groupby("Platform").Year.min()

In [139]:
start_year = start_year.to_frame().reset_index()

In [141]:
start_year = start_year.rename(columns = {'Year' : 'First Year'})

In [142]:
start_year

,Platform,First Year
0,2600,1980.0
1,3DO,1994.0
2,3DS,2011.0
3,DC,1998.0
4,DS,1985.0
5,GB,1988.0
6,GBA,2000.0
7,GC,2001.0
8,GEN,1990.0
9,GG,1992.0


In [145]:
df5 = df.groupby(["Platform", "Year"]).Global_Sales.sum().to_frame().reset_index()

In [146]:
df5

,Platform,Year,Global_Sales
0,2600,1980.0,11.38
1,2600,1981.0,35.77
2,2600,1982.0,28.86
3,2600,1983.0,5.83
4,2600,1984.0,0.27
...,...,...,...
236,XB,2008.0,0.18
237,XOne,2013.0,18.60
238,XOne,2014.0,52.43
239,XOne,2015.0,57.66


In [147]:
df5 = df5.merge(start_year, on="Platform")

In [149]:
df5

,Platform,Year,Global_Sales,First Year
0,2600,1980.0,11.38,1980.0
1,2600,1981.0,35.77,1980.0
2,2600,1982.0,28.86,1980.0
3,2600,1983.0,5.83,1980.0
4,2600,1984.0,0.27,1980.0
...,...,...,...,...
236,XB,2008.0,0.18,2000.0
237,XOne,2013.0,18.60,2013.0
238,XOne,2014.0,52.43,2013.0
239,XOne,2015.0,57.66,2013.0


In [150]:
first_year_sales = df5.loc[(df5.Year == df5["First Year"])]
second_year_sales = df5.loc[(df5.Year == df5["First Year"] + 1)]

In [151]:
end_df = first_year_sales.merge(second_year_sales, on = "Platform")

In [153]:
end_df.loc[end_df.Global_Sales_x > end_df.Global_Sales_y]

,Platform,Year_x,Global_Sales_x,First Year_x,Year_y,Global_Sales_y,First Year_y
2,3DS,2011.0,62.53,2011.0,2012.0,51.14,2011.0
18,SCD,1993.0,1.50,1993.0,1994.0,0.37,1993.0
19,SNES,1990.0,26.16,1990.0,1991.0,16.21,1990.0
